---
title: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Alexander Quinter

Urban Ministries is a non-profit organization that seeks to provide food, job opportunities, and other services to the homeless community of Durham and the surrounding area. Using the data provided by UM, I hope to provide meaningful insight into the services they provide have changed over time, as well as how their services are being utilized
currently. Three variables in the dataset that I believe will be of great importance when analyzing the data are the "Date", "Food.Provided.for", and "Clothing.Items" variables. I currently plan to perform two separate longitudinal analyses on how the amount of food and clothing items provided by UM respectively have changed over time. Upon conducting these analyses, I plan to use R Shiny to make 2 interactive graphs that use a slider to display the average Food Consumption or Clothing Items provided per year, respectfully. I also plan to generate an interactive display comparing average food consumption vs clothing items provided.